--- #YAML:1.0
name:                Sub-Called
version:             0.01
abstract:            Check if a sub has already been called
license:             ~
author:              
    - Curtis "Ovid" Poe <ovid@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
